name: V2Ray + Tailscale Temporary Test

on:
  workflow_dispatch:

jobs:
  run-v2ray:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: تحديث النظام وتثبيت الأدوات
        run: |
          sudo apt update -y
          sudo apt install -y curl

      - name: تثبيت V2Ray
        run: |
          bash <(curl -L -s https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

      - name: إضافة ملف إعداد V2Ray
        run: |
          sudo tee /usr/local/etc/v2ray/config.json > /dev/null << 'EOF'
          {
            "inbounds": [
              {
                "port": 3080,
                "protocol": "socks",
                "settings": { "auth": "noauth", "udp": true }
              },
              {
                "port": 8880,
                "protocol": "http",
                "settings": { "auth": "noauth" }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {},
                "streamSettings": {
                  "network": "ws",
                  "wsSettings": {
                    "path": "/ws",
                    "headers": { "Host": "m.facebook.com" }
                  }
                }
              }
            ]
          }
          EOF
          sudo systemctl restart v2ray

      - name: تثبيت وتشغيل Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=vps-${{ github.run_id }}
          tsIP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
          echo "✅ Tailscale IP: $tsIP"

      - name: إبقاء الخدمة تعمل
        run: |
          while true; do
            echo "[$(date)] V2Ray + Tailscale running..."
            sleep 300
          done
